### ISSUE TITLE
Consider additional measures for reproducible builds

### ISSUE THREAD

**Issue by bollwyvl** [conda/conda-package-handling#1]
The new format sounds like it makes great strides for performance. The other end of moving the package landscape forward is taking any possible opportunities to increase the bit-for-bit reproducibility of the resulting artifacts.

A number of the measures in https://github.com/conda/conda-build/issues/2140 were introduced at various stages, but there are still places where strange paths and file stamps get injected. Especially with the enhanced reproducibility of `pyc` in Python 3.7, this would be a great opportunity to look again at some of these issues.

Keep up the good work!

**Comment by msarahan** [comment]
Thanks for re-raising these.  Some of them can be here, others that deal more with the metadata contents and generation of pyc files will need to be in conda-build.

The collection, for reference, is at https://github.com/conda/conda-build/labels/reproducibility

The ones I think we can do something about here are:
* https://github.com/conda/conda-build/pull/2234 (strip timestamp and user info from files)
* https://github.com/conda/conda-build/pull/2235 (After binsort or filesize sort, sort by filename in case two files are otherwise identical.)

**Comment by msarahan** [comment]
To be clear, this package has absolutely nothing to do with generating pyc files.  I'm trying to keep the separation of concerns stronger.  This library is strictly about packing stuff up and unpacking it.  Removing timestamp and user info might be admissible, but pyc is definitely more than I want in here.  The file sorting is exactly the right kind of thing for this package.

**Comment by bollwyvl** [comment]
:+1: to separation of concerns. Cool label! My point with the `pyc`s is that it was _inconvenient_ to hit predictable builds for many of the python packages before, is easier now, and that this library shouldn't make anything _worse_.  

`.conda` format should aspirationally (maybe with post-processing) be _able_ to be verifiably reproducible, and eventually [tracked](https://tests.reproducible-builds.org/debian/reproducible.html) and preferred. 

Carry on, sir!
