### ISSUE TITLE
Explanation of info- & pkg ordering

### ISSUE THREAD

**Issue by wolfv** [conda/conda-package-handling#182]
I see that the recent release changed the order of `info` and `pkg` archives in the `.conda` format (it's mentioned in the Changelog as well). I tried to go through some PRs but couldn't find the reasoning for the change. Would be curious to hear why this was done :)

**Comment by mbargull** [comment]
Would be good to document this, yes.
I can't say why it was changed. But a good explanation for it is that the outer archive is a Zip file. Hence, the outer archive's index is at the end of the file. So, if you put the `info-*.tar.zst` at the end too, you can fetch the metadata with a single fetch (from disk or (HTTP) server).
(In case of the former `.tar.bz2` you'd want `info` at the beginning of the index-less tarball, of course.)

**Comment by wolfv** [comment]
Hmm, although you don't know beforehand how large the `info.tar.zst` file is, right? You mean one would fetch N bytes and hope that it covers both the `zip-index` and `info.tar.zst` part?

**Comment by dholth** [comment]
conda-package-streaming has good support for reading partial remote zip archives, and using this to get the info out of a conda in a maximum of 3 remote requests.

It was done so that this transmute implementation https://github.com/conda/conda-package-streaming/blob/main/conda_package_streaming/transmute.py#L72 could buffer the usually-small info in memory while writing the pkg- directly to the zip archive.
