### ISSUE TITLE
Support mult-threaded compression.

### ISSUE THREAD

**Issue by asford** [conda/conda-package-handling#53]
The `.conda` pkg format has significant, obvious advantages over the v1 `.tar.bz2` package format. One, potentially significant, advantage of `zstd` is the ability to tune compression levels and (optionally) utilize multicore compression/decompression. 

It's not entirely clear from the current documentation, but it appears that any compression format supported by libarchive is a valid target for `.conda` internal files however only `zstd` compression is currently used.

Compressing with [`python-zstandard`]
(https://github.com/indygreg/python-zstandard), rather than libarchive, would offer support for multi-threaded compression. This would be a major benefit under the current default settings, which use an extremely high zstd compression setting.

**Comment by mingwandroid** [comment]
While a PR would be weclomed, I doubt we will work on this, libarchive supports parallel execution for various formats and adding support to the zstd backend would seem to me to be the best approach here for the greater good (since then things like bsdtar gain that support).

Still, I don't care about compression time here, only compression ratio and splitting blocks for parallelism affects compression ratios negatively.

**Comment by asford** [comment]
Understood, particularly on the preference to update libarchive. In this case all compression control should follow through the current "compression_tuple" configuration mechanism, including control for compression level and multithreaded compression.

Closing, as any follow-up would be strictly doc related.

**Comment by msarahan** [comment]
The major reason not to use multiple cores for compression is the long term goal of reproducible builds: getting the same hash for a recipe build, no matter when our where that build happens. Zstd will result in different hashes depending on the number of cores used (though it is reproducible for a given number of cores).

I think this could be optional, though: default to reproducibility, but allow people to sacrifice it for does it they want.

**Comment by msarahan** [comment]
One other thing to consider about this: what is the right level to apply parallelism at?  Conda-build supports running more than one build at a time (by trying to keep build spaces separate, and by using a file lock around conda operations, which might otherwise corrupt the cache).  If this compression step were parallel, running more than one conda-build at a time might oversubscribe the system.  Same thing for the "transmute" operation here in conda-package-handling - it's designed to process more than one package at a time, and would quickly oversubscribe the system.

Any effort to parallelize zstd is definitely worthwhile, but unfortunately there's a lot of connected pieces to consider.

**Comment by asford** [comment]
🤔 That's an interesting line of though. Our use case with a private repo is different enough from yours (much smaller n-build to n-installed ratio) that issues like byte-for-byte reproducibility of the build artifact or absolute-maximum compression ratio matter less. I can clearly understand how you would be insensitive to compression time, as many of your core packages are getting thousands of download hits.

Would you be open to some follow-up work documenting and formalizing how the current implementation can be modified to control compression parameters? I would certainly benefit from being able to generate v2 packages with faster compression settings in the build process, but don't want to take a strong dependency on undocumented/internal interfaces.

**Comment by msarahan** [comment]
Yes! Absolutely! That would be much appreciated.

Bear in mind that the current implementation is a first stab, and if you see ways to clarify and improve the code, it is very welcome.  Before things are documented, those changes are much easier to make.  One thing on my list is that the current "2" setting for conda-build to enable the different package format is pretty awful.  It should take a list of formats to build, not a single value.  Conda-build should then iterate over that list.

```
conda-build:
  pkg_format:
    - .conda
    - .tar.bz2
```

This should be a quick improvement, but unfortunately we just haven't had time to spend on it.

**Comment by dholth** [comment]
@asford this will be supported in conda-package-handling 2.0. It may help with the largest packages. I wasn't able to notice a difference with pillow.
