### ISSUE TITLE
Critcal bug: failure to extract some tar.bz2 files.

### ISSUE THREAD

**Issue by FaustinCarter** [conda/conda-package-handling#60]
For some reason, some files are not extracting properly, even though they are valid files. This is causing massive errors when trying to use `conda-index` to build a repository index. I'm not sure what the issue is, and why some files are fine, and others aren't, but here are two representative files.

One that works:
https://repo.anaconda.com/pkgs/main/linux-64/absl-py-0.4.1-py35_0.tar.bz2

And one that doesn't:
https://repo.anaconda.com/pkgs/main/linux-64/git-2.16.1-hb75a9fb_0.tar.bz2

Succeeds:
``` python
import conda_package_handling.api as api
api.extract('absl-py-0.4.1-py35_0.tar.bz2')
```

Fails to extract:
``` python
import conda_package_handling.api as api
api.extract('git-2.16.1-hb75a9fb_0.tar.bz2')
```
Throws the following error:

```
InvalidArchiveError: Error with archive git-2.16.1-hb75a9fb_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:

Can't create '\\?\C:\Users\fwcarter\Downloads\git-2.16.1-hb75a9fb_0\libexec\git-core\git-remote-ftp' (errno=22, retcode=-25, archive_p=1764784645168)
```
However, attempting to open this file with `tarfile` presents no problem at all.

I'm currently on a Windows 10 box using an environment created via:

```
conda create -n foo python=3.7 conda-build
```

With:
```
conda version : 4.8.3
conda-build version : 3.18.11
python version : 3.7.7.final.0
```

**Comment by FaustinCarter** [comment]
Possible fix involves running a second pass on `InvalidArchiveError` that sets `libarchive_enabled=False`, thus falling back to tarfile.

https://github.com/conda/conda-package-handling/blob/720335f7407599a8b62c1c8b875d86f925558725/src/conda_package_handling/tarball.py#L134-L137

Or update to a more recent build of libarchive that doesn't have this issue...

**Comment by FaustinCarter** [comment]
After much testing, this turns out to be an issue with files that contain symbolic links, and Windows policy of not granting users symlink permission.

I'm changing this to a request to explicitly add a note in the documentation about requiring an elevated prompt on windows in order to run conda-package-handling scripts.

**Comment by mingwandroid** [comment]
This is interesting, where'd you get this git package from? We may need to be careful about symlinks on Windows creeping into our packages!

**Comment by FaustinCarter** [comment]
That package was pulled straight from the main Anaconda repository (https://repo.anaconda.com/pkgs/main/linux-64). There are quite a few (maybe a couple hundred?) packages in the linux-64 channel that have a similar "problem". It's really not an issue for linux/osx systems, but when trying to index and host a mirror on a Windows server that needs to serve a linux user-base as well, it's a huge annoyance.

**Comment by mingwandroid** [comment]
We've always explicitly been done with symlinks on unix. It's only on windows where Microsoft chickened out!

**Comment by desilinguist** [comment]
I seem to be running into a related error with .tar.bz2 extraction but on window and linux. We have a conda data package that we built a while ago (in 2015). The package has just a serialized language model file in and nothing else. Recently, we discovered that the package will no longer install and fails with the error ('Seek failed"). While poking around in the `conda_package_handling` directory, I found `libarchive_enabled` flag and forced it to be turned on by deleting the `archive_utils` python and cython so files. Lo and behold, the package installation worked just fine then. 

I have a feeling that the _correct_ solution is to _rebuild_ the data package so that it's created using libarchive? Any guidance would be most welcome.

**Comment by AlexLabram** [comment]
I'm pretty sure this issue has been prematurely closed.  As of package version "git-2.34.1-pl5262hc120c5b_0.tar.bz2" (per the [repo folder](https://repo.anaconda.com/pkgs/main/linux-64/git-2.34.1-pl5262hc120c5b_0.tar.bz2)), the package still contains on the order of a hundred embedded simlinks, which - per the [related git-cola issue](https://github.com/ContinuumIO/anaconda-issues/issues/12715) I've logged and @FaustinCarter's sterling detective work - will still consistently cause conda package handling to fall over on Windows systems with user-level access.  If Anaconda is expected to work in a mixed Linux/Windows corporate environment, as used by the original poster, the problem should be fixed rather than just marked stale.

I think it's worth leaving both issues open since the suggested resolutions are different: the git-cola issue just needs a simlink replaced with a copy of the underlying 9KB file (five minutes' work - hint hint!), whereas this package needs warning labels slapped on.  The fact that there _are_ two issues suggests that it may also be appropriate to have conda-build return a warning when creating a package containing symlinks; I don't know whether it'd be appropriate to log a third issue for this?
